### ISSUE TITLE
Feature Request: Choose corner for Tramming Reference.

### ISSUE THREAD

**Issue by Moobien** [mriscoc/Ender3V2S1#119]
**Is your feature request related to a problem? Please describe.**
Often when I am tramming by bed I will be prompted to tram my rear left corner, I adjust other corners instead as my rear left has the wiring harness so I try to adjust it as little as possible.

**Describe the solution you'd like**
The ability to choose a corner to use as a reference for tramming against.  If corner X is chosen as a reference corner, the other 3 corners will tram against it instead of against each other.

**Comment by SmallTownSound** [comment]
+1 for that, please add it.

**Comment by mriscoc** [comment]
Currently the reference is the average of the four corners, that allows faster tramming, I recommend starting with the other corners above the problematic one.

**Comment by SmallTownSound** [comment]
Not a problematic corner.  The left back corner should always be used as a reference since it has the least travel, and should always be used as the reference. Sent from Mail for Windows From: Miguel Risco-CastilloSent: Sunday, May 29, 2022 6:06 PMTo: mriscoc/Ender3V2S1Cc: Don Turnock; CommentSubject: Re: [mriscoc/Ender3V2S1] Feature Request: Choose corner for Tramming Reference. (Issue #119) Currently the reference is the average of the four corners, that allows faster tramming, I recommend starting with the other corners above the problematic one.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
