### ISSUE TITLE
Wierd noises from Motherboard(i think) when trying to use preheat PLA

### ISSUE THREAD

**Issue by BuzzBill** [mriscoc/Ender3V2S1#162]
**Describe the bug**
i just tried to preheat the printer using the preheat  PLA and immediately wierd noises. Everything else works fine.

**Version  Latest Version

**Comment by BuzzBill** [comment]
**Update  
i opened the board case and the fan is making the noise every 2-3 seconds a sound like a wild spin...
The printer is brand new and made no noise until today

**Comment by mriscoc** [comment]
The board fan is connected in parallel with the part cooling fan, you can test it in Control / Temperature / Fan speed.
![temperature](https://user-images.githubusercontent.com/2745567/169549065-5a275113-4111-4471-af69-6ea8307bbac4.jpg)
Some fans start to make sounds after some time of use or because dust accumulation.
It is not a firmware issue.
