### ISSUE TITLE
BUG on Start New Print.

### ISSUE THREAD

**Issue by pacocatech** [mriscoc/Ender3V2S1#196]
When I click print, the firmware update message appears.

See the video, I'm using the version with BLTOUCH.

https://drive.google.com/file/d/1hpIaxUF9s5XLgrc3daU9g7BYnBe1wQWA/view?usp=sharing

My board is 4.2.2

**Comment by mriscoc** [comment]
The video doesn't show your bug.

**Comment by pacocatech** [comment]
Sorry, i posted wrong video, this is correct: https://drive.google.com/file/d/18cDZCn82P1qszG-3-w0zkJFHTdvf-tk4/view

**Comment by locksen-nl** [comment]
I have the same problem also 4.2.2 with a bltouch

**Comment by mriscoc** [comment]
Seems to be a problem with some kind of memory cards, try with other SD card, format to FAT32, put no more of 20 files on it.

**Comment by pacocatech** [comment]
I even thought it could be the card, I got a new class 10 card, formatted it as FAT32 because NTFS doesn't work and just added the firmware and then formatted it again and left a maximum of 4 files and the problem still persists.
In the old firmware version this does not happen.

**Comment by mriscoc** [comment]
Please, can you specify what precompiled version you are using?

**Comment by pacocatech** [comment]
this version: [Ender3V2-422-BLT-20220527.bin](https://github.com/mriscoc/Ender3V2S1/releases/download/20220527/Ender3V2-422-BLT-20220527.bin)

**Comment by esrpradeep** [comment]
I have the same problem after upgrading to Ender3V2-427-BLT-20220527.bin. Remove the 'SDCard' as a workaround and press 'Print' - ignore the 'No Media' message. While still in the 'Print' menu screen, insert the 'SDcard' to select and print the desired file.

**Comment by faucherc** [comment]
I have the same problem after upgrading to [Ender3V2-422-BLT-20220527.bin](https://github.com/mriscoc/Ender3V2S1/releases/download/20220527/Ender3V2-422-BLT-20220527.bin).  I have a 4.3.1 mainboard and a DACAI display.

I have tried with 2 different SD Card and I have seen the problem with both of them.  I never encontered this kind of problem with these 2 cards with the Creality stock firmware.

When the problem occurs, generally, it occurs only one time instead of many time like in pacocatech video's.

**Comment by mriscoc** [comment]
Please verify with latest version.

**Comment by Moobien** [comment]
This was the same Issue I reported a few weeks back.  Card was completely fine.

**Comment by esrpradeep** [comment]
> I have the same problem after upgrading to Ender3V2-427-BLT-20220527.bin. Remove the 'SDCard' as a workaround and press 'Print' - ignore the 'No Media' message. While still in the 'Print' menu screen, insert the 'SDcard' to select and print the desired file.

Update: Upgraded to Ender3V2-427-BLT-20220716.bin, and I haven't observed the 'SDCard' issue so far.

Observation from my end: 

JULY2022 release has the SDSORT_LIMIT as '40' in the file 'Configuration_adv.h' compared to May2022 release that had '60' for Ender3V2-427-BLT under the link 'Special_Configurations'.

Latest 'Configuration_adv.h' from Special configurations
#define SDSORT_LIMIT       40     // Maximum number of sorted items (10-256). Costs 27 bytes each.  // MRiscoC Increase number of sorted items

I'm not sure if this was the root of the problem or could have been resolved due to the latest Marlin bugfix branch.

**Comment by mriscoc** [comment]
SDSORT_LIMIT is only a limit value, I reduced it for cases where the SD card has a large amount of files and the memory limit could be exceded.
I think that the error could comming from the Marlin core.

**Comment by mriscoc** [comment]
Print File menu list has been improved in the last version, please test.

**Comment by mriscoc** [comment]
No more user feedback.
