### ISSUE TITLE
Setting multi probe to 1 causes probing failure 

### ISSUE THREAD

**Issue by Neilridley** [mriscoc/Ender3V2S1#223]
Tried setting probe number to 1 and probing failed, high speed mode in ticked, was deploying probe without lifting Z axis, Ender S1 on F1 chip

**Comment by BytewaveMLP** [comment]
Can reproduce on Ender 3 V2, Creality 422 mainboard.

**Comment by mriscoc** [comment]
Thank you for you report. I didn't try with 1 (my mistake) but 0, means no multiprobe, then only one probe. 2 means two probe plus one extra to discard the fartest from mean value.

Setting to one not has a meaning, because it is not posible to do an average to do the comparison with the extra probing.

So, one is a forbidden setting.

**Comment by Neilridley** [comment]
No problem I’ll keep it on 2

**Comment by mriscoc** [comment]
Fixed in the latest version.
