### ISSUE TITLE
Stepper drivers very loud since July Firmware

### ISSUE THREAD

**Issue by lackY0704** [mriscoc/Ender3V2S1#256]
Since July's firmware, the stepper drivers have been very loud.
Nothing changes if I change the values ​​as already described. If I play the firmware from May 22, everything is quiet again. Tested with  motherboards 4,2,2 and 4,2,7
Especially in large objects and many curves. It's extreme in the corners

**Comment by neshami** [comment]
On every diagonal move stepper motors are very loud on latest firmware.  Ender 3S1 F103 board. So diferent behavior from firmware before this latest.
What is the cause?

Få Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: lackY0704 ***@***.***>
Sent: Friday, July 29, 2022 11:02:52 AM
To: mriscoc/Ender3V2S1 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mriscoc/Ender3V2S1] Stepper drivers very loud since July Firmware (Issue #256)


Since July's firmware, the stepper drivers have been very loud.
Nothing changes if I change the values ​​as already described. If I play the firmware from May 22, everything is quiet again. Tested with motherboards 4,2,2 and 4,2,7
Especially in large objects and many curves. It's extreme in the corners

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/issues/229
