### ISSUE TITLE
Screen shows distorted numbers or UI Artifacts

### ISSUE THREAD

**Issue by thesebastianf** [mriscoc/Ender3V2S1#359]
sorry - no clue how to reproduce.
installed firmware is Ender3 V2/S1 Professional Firmware 20220816
on a Ender 3 V2 4.2.2 BLTOUCH

on a very long print - after 12 hours the display started to show numbers in big letters randomly on the screen
see screenshot top and down area

![image](https://user-images.githubusercontent.com/13987575/189484448-a51b4395-d61a-42ef-8767-4e47b57cea7a.png)

**Comment by mriscoc** [comment]
That screen glitch is due to interference in the cable between the control board and the screen, sadly that cannot be fixed by firmware, some users report that using a ferrite ring (choke) can help with that issue. Also, check that cable and re-route it.
The glitch can be cleared using the turn on/off screen in the Advanced or Tune menus.

If you are using Octoprint or another host as Repetier check this guide: https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint and be sure that you remove the +V pin from the USB.

**Comment by lagnat** [comment]
I had this happen yesterday right after installing this firmware.  Never once happened before.  Just my $.02.

**Comment by mriscoc** [comment]
> I had this happen yesterday right after installing this firmware. Never once happened before. Just my $.02.

Stock Creality firmware sends less information to the screen while it's printing, so failures are less likely.

**Comment by lagnat** [comment]
Less information?  Never had the problem with Jyers either.  I'll try the ferrite.  What about a shielded cable?

**Comment by mriscoc** [comment]
> Less information? Never had the problem with Jyers either. I'll try the ferrite. What about a shielded cable?

This firmware may not be compatible with your hardware, I recommend going back to a functional firmware.

**Comment by lagnat** [comment]
Ender3V2, v4.2.2 board

**Comment by mriscoc** [comment]
Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/328
