### ISSUE TITLE
Printer hangs with an own firmware compiled with some changes in source code for Ender-3 S1 and F4 SoC

### ISSUE THREAD

**Issue by pacocatech** [mriscoc/Ender3V2S1#501]
Hello, I'm using the newest version of your firmware on an S1F4, however, when you restart the machine this message appears, why does this happen?

![image](https://user-images.githubusercontent.com/70729684/201401376-19e50901-9815-4410-b43f-9b749b3085db.png)

**Comment by ghost** [comment]
> Hello, I'm using the newest version of your firmware on an S1F4, however, when you restart the machine this message appears, why does this happen?
> 
> ![image](https://user-images.githubusercontent.com/70729684/201401376-19e50901-9815-4410-b43f-9b749b3085db.png)

This error is due to a problem with the temperature sensor. Often with the movement of the printer, the screw that fixes it closes short on the terminals and gives this problem.
Remove the screw and insulate this point.

**Comment by pacocatech** [comment]
I was using the normal printer, after I updated the version this message started to appear, the only change I made was to adjust the machine name within the source code.

**Comment by classicrocker883** [comment]
do other firmware versions work? because I would get this error when something wasnt grounding correctly.

even plugging in a USB would cause such an error. the fix was to reseat the mainboard.

you can test this by turning the printer on its side, open the bottom panel where the mainboard is and unmount it. have the board dangle with all the wires still plugged in. just becareful and aware of the wires that they arent shorting or touching anything else. 
the reason for the error to me as the board somehow grounded on the frame. you can use felt pads, electrical tape / glue, anything so the board isnt touching the frame and the screws arent either. if u have a felt washer to put on the screw. if u still get the error and confirmed its this, try turning the screw to mount it not so tight.

**Comment by CorDawg** [comment]
I had this happen twice today on my Ender 3 S1 (F1 Chipset) but I do not know if it could be the thermistor. Is this error because a secondary thermal cutoff switch in the printhead? Because other then a slight erratic temperature graph when it happened, octoPrint never showed a temperature higher than ~245C (my setpoint)

**Comment by CorDawg** [comment]
I just had similar thing happen today twice on other printer (Ender 3 S1 F4 Chipset) "Heating failed, system stopped! Heater_ID: E0 -" in octoprint. but this looks like heater failure error, not max temp error.

Edit: it also maxtemp errored. One of the times I saw it started printing and then shot up from 245 to 275 before maxtemp error.  After rebooting the printer twice, it seems to be working fine again. I'm printing 245C and 80C bed.

My prints turn out perfectly on these machines, I have never had these errors before this release, both printers are connected to their own seperate UPS's. The F1 is connected to an orangepi and the F4 is connected to a raspberry pi 400. The prints still turn out perfectly, but I would hate for this error to crop up when I am not nearby (if it is firmware related)

![printertemp](https://user-images.githubusercontent.com/47271241/202735696-b210a43e-677c-49f5-a9aa-a7ee10fb651a.png)

**Comment by CorDawg** [comment]
To follow-up on previous post, the hotend on the S1 F4 became clogged much later in the day (was printing fine after the error). I have changed the nozzle and its continuing to print well. The S1 F1 chipset is still printing perfectly ever since the errors on it without hiccup. I can't say that I think its the firmware still, especially if there are not a lot of reports. Maybe these hotends are due for a disassembly and cleaning, but I will probably upgrade to the pro sprite hotends when I think they have started to deteriorate. I don't know what the expected life span is on these sprite extruders. I print PETG and TPU with them.

**Comment by mpohoda** [comment]
S1 F4 same problem, clean fw with changed printer name only

**Comment by KBalage** [comment]
Yes, happened again after a cold start. I can't start the printer at all - it's doing it again and again, and the only workaround is to apply a new firmware (every day?).

**Comment by mriscoc** [comment]
It could be a problem with a new bootloader in new printers. Go back to the Creality official firmware for now.

**Comment by KBalage** [comment]
No, never, I'd rather refresh this one every day than go back tot he official - this one is hundreds more useful.

**Comment by KBalage** [comment]
Update - it doesn't happened this morning - but I'm using the precompiled/downloaded Ender3S1-F4-20221002.bin version this time.
It happens only with own compiled versions (despite having minimal changes in configuration.h).

**Comment by mpohoda** [comment]
Looks like that problem was with BED_MINTEMP and BED_MAXTEMP.

With this setup is everything good:
#define BED_MINTEMP        0  // Ender Configs
#define BED_MAXTEMP      120  // Ender3S1 Configs

**Comment by Wassabichan** [comment]
don`t know if this is the same issue, but i can`t build my own marlin out of the newest source code (building seems fine, but when i flash my printer with the compiled software, it bootfreezes and is heating the bed uncontrollable

**Comment by Wassabichan** [comment]
the premade updates are working, i have the F1
