### ISSUE TITLE
Synchronise bed and nozzle heating

### ISSUE THREAD

**Issue by tonysprenk** [mriscoc/Ender3V2S1#61]
**Is your feature request related to a problem? Please describe.**
The nozzle on my ender 3 v2 is always much faster to reach temperature than the bed, resulting in filament wastage as some always "drips out" while heating

**Describe the solution you'd like**
Not sure if this is even possible but: it would be nice to have a (self learning) mechanism implemented that makes sure that the bed and nozzle reach the desired temperature simultaneously. 

**Describe alternatives you've considered**
An alternative could be to change the starting code to have the bed fully heat first and then start heating the nozzle but this would take a lot longer.

**Comment by mriscoc** [comment]
The slicer puts a g-code M190 to wait for the target bed temperature to be reached, that is because the bed takes a long time to reach a thermal stability due to its large mass. If you don't want to wait, change the M190 for M140.https://marlinfw.org/docs/gcode/M190.html

You can do a little retract at the end of the print for avoid drips.
