### ISSUE TITLE
Print how to recover after power failure

### ISSUE THREAD

**Issue by zkbutt** [mriscoc/Ender3V2S1#627]
**Describe the bug**
Print how to recover after power failure?  Restart the machine without any prompt

**To Reproduce**
Related configurations have been enabled. I do not know whether they are correct
Printed from octoprint. Non-sd card

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/18031838/211180459-a38451d3-6ff1-4dc7-8a71-8b053fb49b2a.png)

**Version (please complete the following information):**
Experimental-Ender3S1-F4-T13-20221002

**Additional context**

**Comment by Matrixchung** [comment]
It seems that Octoprint doesn't know where the printer head actually is because of serial lag, which makes power loss recovery nearly impossible.
See: 
* https://community.octoprint.org/t/power-loss-recovery-with-op/32360
* https://community.octoprint.org/t/recovery-from-power-failure/27995

However, you may achieve this through adding a UPS module to support the host (usually a Raspberry Pi) running and **pausing** the current job. In that case, you need to communicate with your UPS and determine when to pause the print and you must keep your host running through battery power because after the host is killed, all ongoing process (including paused print) will lost.
See:
* https://community.octoprint.org/t/setup-ups-with-intelligent-power-loss-recovery/37333
