### ISSUE TITLE
PrusaSlicer thumbnails not interpreted correctly

### ISSUE THREAD

**Issue by 400Ferrets** [mriscoc/Ender3V2S1#672]
**Describe the bug**
PrusaSlicer thumbnails do not work

**To Reproduce**
Try using a thumbnail generated by PrusaSlicer on v2.5.0

**Expected behavior**
Thumbnail is shown

**Version (please complete the following information):**
Ender3V2-422-MM-MPC-20221222

**Additional context**
The thumbnails do not work because PrusaSlicer puts "thumbnail_JPG" in the image header and the printer looks for just "thumbnail". using PNG mode puts the correct header but the printer complains and won't display the image. manually removing "_JPG" in the gcode file fixes the issue and the printer displays the thumbnail.

A fix would be making the firmware look for "thumbnail_JPG" as well as "thumbnail" when finding encoded images.

BAD:
![image](https://user-images.githubusercontent.com/68585283/214213851-150daeb9-3528-4d1a-befc-222ad1011dfb.png)

FIXED:
![image](https://user-images.githubusercontent.com/68585283/214213897-9a11ff3f-cae9-40bd-a238-70d488a83b55.png)

**Comment by mriscoc** [comment]
If you set PNG in PrusaSlicer and the printer does not show the preview, then the python script is not working in your setup.
The post processing script expect an image in PNG format, converts it to JPG and adds a header to show estimated time, filament used, etc.
That PNG to JPG conversion was necessary because old PrusaSlicer and SuperSlicer only support PNG and the printer only reads JPG.
