### ISSUE TITLE
Sprite Extruder Pro build missing for 4.2.7 board

### ISSUE THREAD

**Issue by webdeck** [mriscoc/Ender3V2S1#933]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

The 4.2.7 version of the Sprite Extruder Pro special configuration has gone missing with the latest release.  See https://github.com/mriscoc/Special_Configurations/releases/tag/T13

### Bug Timeline

New issue with latest releae

### Expected behavior

Expected download link for Ender3V2-427-BLTUBL-T13-MPC-20230524.bin

### Actual behavior

422 builds are available, but 427 is missing

### Steps to Reproduce

1. Go to https://github.com/mriscoc/Special_Configurations/releases/tag/T13

### Version of Professional Firmware

20230524

### Printer model

Ender 3V2

### Electronics

4.2.7

### Add-ons

Sprite Extruder Pro, BL Touch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
It's not a firmware problem.
Sorry, but due to more firmware variations (CVLM, TJC, etc.) I can't compile as many versions for free anymore. So I prioritized versions with more downloads.

[How to request a custom build](https://github.com/mriscoc/Special_Configurations#how-to-request-a-custom-build)
